Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (1,'Start of load for referencedata.');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (2,'End of load for referencedata, 372 lines.');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (3,'The reference XML nodes is ready...');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (1,'1. Make sure file is read file...');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (2,'2. Start create tables...');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (3,'enter the create tables procedure');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (4,'Total of allowed station nodes in input  .. = 81');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (5,'Total Stations imported in database(rc_topologyelement) : 60 .');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (6,'Total of not allowed station nodes in input  .. = 99');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (7,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (8,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (9,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (10,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (11,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (12,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (13,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (14,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (15,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (16,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (17,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (18,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (19,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (20,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (21,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (22,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (23,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (24,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (25,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (26,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (27,'the station type: OOG_Out  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (28,'the station type: OOG_Out  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (29,'the station type: OOG_Out  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (30,'the station type: HBS_3  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (31,'the station type: HBS_3  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (32,'the station type: OOG_Out  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (33,'the station type: OOG_Out  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (34,'the station type: OOG_Out  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (35,'the station type: OOG_Out  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (36,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (37,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (38,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (39,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (40,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (41,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (42,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (43,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (44,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (45,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (46,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (47,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (48,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (49,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (50,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (51,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (52,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (53,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (54,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (55,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (56,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (57,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (58,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (59,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (60,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (61,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (62,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (63,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (64,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (65,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (66,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (67,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (68,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (69,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (70,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (71,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (72,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (73,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (74,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (75,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (76,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (77,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (78,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (79,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (80,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (81,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (82,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (83,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (84,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (85,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (86,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (87,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (88,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (89,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (90,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (91,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (92,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (93,'the station type: CheckIn  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (94,'the station type: VolumeScan  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (95,'the station type: AutoScan  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (96,'the station type: VolumeScan  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (97,'the station type: AutoScan  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (98,'the station type: VolumeScan  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (99,'the station type: AutoScan  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (100,'the station type: VolumeScan  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (101,'the station type: AutoScan  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (102,'the station type: VolumeScan  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (103,'the station type: AutoScan  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (104,'the station type: VolumeScan  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (105,'the station type: VolumeScan  is skipped for loading into SM');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (106,'End the creating tables procedure');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (107,'End of load script for referencedata.');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (108,'Start of load for referencedata.');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (109,'End of load for referencedata, 55 lines.');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (110,'The reference XML nodes is ready...');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (1,'1. Make sure file is read file...');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (2,'2. Start create tables...');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (3,'enter the create tables procedure');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (4,'Total of allowed station nodes in input  .. = 45');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (5,'Total Stations imported in database(rc_topologyelement) : 105 .');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (6,'Total of not allowed station nodes in input  .. = 0');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (7,'End the creating tables procedure');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (8,'End of load script for referencedata.');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (9,'Start of load for referencedata.');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (10,'End of load for referencedata, 71 lines.');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (11,'The reference XML nodes is ready...');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (1,'1. Make sure file is read file...');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (2,'2. Start create tables...');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (3,'enter the create tables procedure');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (4,'Total of allowed station nodes in input  .. = 61');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (5,'Total Stations imported in database(rc_topologyelement) : 166 .');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (6,'Total of not allowed station nodes in input  .. = 0');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (7,'End the creating tables procedure');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (8,'End of load script for referencedata.');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (9,'Start of load for referencedata.');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (10,'End of load for referencedata, 44 lines.');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (11,'The reference XML nodes is ready...');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (1,'1. Make sure file is read file...');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (2,'2. Start create tables...');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (3,'enter the create tables procedure');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (4,'Total of allowed station nodes in input  .. = 18');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (5,'Total Stations imported in database(rc_topologyelement) : 184 .');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (6,'Total of not allowed station nodes in input  .. = 0');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (7,'End the creating tables procedure');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (8,'End of load script for referencedata.');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (9,'Start of load for referencedata.');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (10,'End of load for referencedata, 138 lines.');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (11,'The reference XML nodes is ready...');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (1,'1. Make sure file is read file...');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (2,'2. Start create tables...');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (3,'enter the create tables procedure');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (4,'Total of allowed station nodes in input  .. = 117');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (5,'Total Stations imported in database(rc_topologyelement) : 301 .');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (6,'Total of not allowed station nodes in input  .. = 0');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (7,'End the creating tables procedure');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (8,'End of load script for referencedata.');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (9,'Start of load for referencedata.');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (10,'End of load for referencedata, 8 lines.');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (11,'The reference XML nodes is ready...');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (1,'1. Make sure file is read file...');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (2,'2. Start create tables...');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (3,'enter the create tables procedure');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (4,'Total of allowed station nodes in input  .. = 2');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (5,'Total Stations imported in database(rc_topologyelement) : 303 .');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (6,'Total of not allowed station nodes in input  .. = 0');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (7,'End the creating tables procedure');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (8,'End of load script for referencedata.');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (9,'Start of load for referencedata.');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (10,'End of load for referencedata, 6185 lines.');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (11,'The reference XML nodes is ready...');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (1,'1. Make sure system config file is read file...');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (2,'2. Start to insert handler...');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (3,'enter initial static data handlers procedure');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (4,'project_definition//HandlerList//Handler');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (5,'End the initial static data handlers procedure');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (6,'End of load script for system config.');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (7,'The reference XML nodes is ready...');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (1,'1. Make sure system config file is read file...');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (2,'2. Start to insert lutype...');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (3,'enter initial static data luTypes procedure');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (4,'project_definition//LoadUnitList//LoadUnit');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (5,'End the initial static data luTypes procedure');
Insert into RC_REF_DATA_LOG (ID,LOG_MSG) values (6,'End of load script for system config.');