DELETE FROM rc_area;
INSERT INTO RC_AREA(OID, NAME, OSOCIDENTIFICATION, CONTROLLED) VALUES (11, 'Zuid', 'Z', '1');
INSERT INTO RC_AREA(OID, NAME, OSOCIDENTIFICATION, CONTROLLED) VALUES (1, 'West', 'W', '1');
INSERT INTO RC_AREA(OID, NAME, OSOCIDENTIFICATION, CONTROLLED) VALUES (2, 'D-pier', 'D', '1');
INSERT INTO RC_AREA(OID, NAME, OSOCIDENTIFICATION, CONTROLLED) VALUES (3, 'T2', 'C', '1');
INSERT INTO RC_AREA(OID, NAME, OSOCIDENTIFICATION, CONTROLLED) VALUES (4, 'E-pier', 'E', '1');
INSERT INTO RC_AREA(OID, NAME, OSOCIDENTIFICATION, CONTROLLED) VALUES (5, 'BackBone', 'B', '1');