--WHENEVER SQLERROR EXIT FAILURE ROLLBACK;

--\i ps/data/DEFAULTHANDLERPLANSETTING

--execute defaultHandlerPlanSetting;

insert into PS_BAGGAGEHANDLERPLAN (OID, STARTDATE) values (nextval('SEQ_PSBAGGAGEHANDLERPLAN'), TO_Date( '01/01/1970', 'MM/DD/YYYY'));
insert into ps_outboundareaassignmentplan(oid,startdate) values (Nextval('SEQ_OAP'),to_date('1970-1-1','yyyy-MM-dd'));
INSERT INTO PS_OUTBOUNDAREAASSIGNMENTRULE (OID,PLANOID,ORDERNUMBER,FLIGHTPREFIXSPECIFIER,FLIGHTSUFFIXSPECIFIER,NUMBEROFSEATSSPECIFIER,AIRCRAFTTYPESPECIFIER,RANGESPECIFIER,STDSPECIFIER,AREAOID)
						                              VALUES(nextval('SEQ_PSOUTAREAASSIGNMENTRULE'),CURRVAL('SEQ_OAP'),100,'*','*','*','*','*','*',11);
INSERT INTO PS_INBOUNDAREAASSIGNMENTRULE ( OID, PLANOID,ORDERNUMBER, FLIGHTPREFIXSPECIFIER,
FLIGHTSUFFIXSPECIFIER, NUMBEROFSEATSSPECIFIER, AIRCRAFTTYPESPECIFIER, RANGESPECIFIER, STDSPECIFIER,
EURAREAOID, ICAAREAOID, SHOCONAREAOID ) VALUES ( 
nextval('SEQ_PSINAREAASSIGNMENTRULE'), CURRVAL('SEQ_OAP'), 1000, '*', '*', '*', '*', '*', '*', 11, 11, 11); 	

--BAS00051380
update PS_HANDLER set HANDLER_KIND=0;
update PS_HANDLER set HANDLER_KIND=1 where name in ('KLM','QQO','QQP','QQN','QQG','QQB');	

--BAS00060792
update PS_HANDLER set ALLOWEDAREAS = 'BackBone,West,D-pier,Zuid,E-pier,T2' where NAME not like 'SEC';
update PS_HANDLER set ACTIVE =  'Y';
update ps_handler set ACTIVE =  'N' where NAME = 'SEC';
update PS_HANDLER set ORGANIZATION = 'QQN' where NAME in ('QQO','QQP','QQG','QQN','QQB','BAW','DAL','DLH','ELY','IBE','MPH','QQA','QQD','QQF','QQR','QQH','QQJ','QQU','QQW','QQZ','TRA','DHL','QQC','QQQ','QQS','QQV','QQX');
update PS_HANDLER set ORGANIZATION = 'KLM' where NAME in ('KLM','KLJ','KLP');
update PS_HANDLER set COLOR = '0,191,255' where NAME= 'KLM';
update PS_HANDLER set COLOR = '240,230,140' where NAME= 'QQO';
update PS_HANDLER set COLOR = '255,218,185' where NAME= 'QQP';
update PS_HANDLER set COLOR = '219,112,147' where NAME= 'QQG';
update PS_HANDLER set COLOR = '255,215,0' where NAME= 'QQN';
update PS_HANDLER set COLOR = '179,238,58' where NAME= 'QQB';

--commit;