

-- After renaming action
DROP TABLE IF EXISTS RC_SORTERMAPPING CASCADE; 
DROP TABLE IF EXISTS RC_LATERAL CASCADE; 
DROP TABLE IF EXISTS RC_OUTPUTPOINT CASCADE; 
DROP TABLE IF EXISTS RC_TOPOLOGYDISTANCE CASCADE; 
DROP TABLE IF EXISTS RC_ROUTINGDESTINATION CASCADE; 
DROP TABLE IF EXISTS RC_PRODUCTDESTINATION CASCADE; 
DROP TABLE IF EXISTS RC_TOPOLOGYELEMENT CASCADE; 
DROP TABLE IF EXISTS RC_AREA CASCADE; 

DROP TABLE IF EXISTS RC_LOGICALMAINTENANCESEGMENT CASCADE; 
DROP TABLE IF EXISTS RC_MAINTENANCESEGMTOPELT CASCADE; 
-- After renaming action

DROP TABLE IF EXISTS RC_STAND CASCADE;
DROP TABLE IF EXISTS RC_FLIGHT_RANGE_MAPPING CASCADE;
DROP TABLE IF EXISTS RC_RESOURCESETTINGS  CASCADE;


DROP SEQUENCE IF EXISTS SEQ_LOGICALMAINTENANCESEGMENT CASCADE;
DROP SEQUENCE IF EXISTS SEQ_STAND CASCADE;
DROP SEQUENCE IF EXISTS SEQ_RCRESOURCESETTINGS CASCADE;

--WHENEVER SQLERROR EXIT FAILURE ROLLBACK;


