DROP TABLE IF EXISTS rc_ref_data_log CASCADE;
DROP TABLE IF EXISTS rc_ref_data CASCADE;
DROP TABLE IF EXISTS rc_top_en_data CASCADE;
--drop sequences
DROP SEQUENCE IF EXISTS SEQ_TOPOLOGYELEMENTOID;




